apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: worker-dep
spec:
  selector:
    matchLabels:
      app: demucs
      tier: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: demucs
        tier: worker
    spec:
      containers:
      - name: demucs-worker
        image: rachna27/demucs-worker:latest
        env:
        - name: REDIS_SERVICE_HOST
          value: redis
        - name: MINIO_SERVICE_HOST
          value: minio
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
---